### ISSUE TITLE
Add "SNAP/WIC Retailers" to drop down menu

### ISSUE THREAD

**Issue by jayktee** [dcl-covid-19/mega-map-dev#1]
Separate "What do you need" drop-down menu into 3 options: “Free Groceries”, “Prepared Meals” (as-is), and “SNAP/WIC Retailers”

- “SNAP/WIC Retailers”: `resource `= grocery and `free` = 0
- "Free Groceries": `resource` = grocery and `free `= 1

**Comment by mfincker** [comment]
@jayktee  - There is currently no free groceries in the database. Is that right/normal?

Also, does the order of the categories in the dropdown matter?

**Comment by jayktee** [comment]
@mfincker I just edited my comment, i meant that the category "Free Groceries" : `resource` = grocery and `free` = 0. Does that make more sense now? 

There is a `free_groceries` column but we are not using that now.

I don't think the order of categories matters.

**Comment by mfincker** [comment]
New categories are:

* Free prepared meals
* Free groceries
* SNAP/WIC retailers
