### ISSUE TITLE
Improve design for EditForm

### ISSUE THREAD

**Issue by mfincker** [dcl-covid-19/mega-map-dev#29]
__Branch: `edit-details-form`__

**Need work on an existing feature? **
There is now a "Suggest an edit" link at the bottom of each expanded location card in case users want to report issues in the data.

When clicked, a form should open and let the users modify the information related to the selected location. The form posts the modified info to a google form (at the moment) when submitted.

(a) Describe the outcome needed/goal of the feature.
I haven't styled the EditForm yet and would appreciate if someone could improve on the design, maybe @topherauyeung if you're interested?

(b) What do we need to code next?
- style the EditForm
- style the "suggest_an_edit" link (but don't make it an <a> tag because otherwise the router changes the url)

**Additional context**
The EditForm feature is not yet on master, but can be found in the  `edit-details-form` branch.

**Comment by topherauyeung** [comment]
Grabbing this today!

**Comment by mfincker** [comment]
Fixed the last two missing functions and merged into master. Thanks @topherauyeung !
