### ISSUE TITLE
Deprecate 'meal_senior', 'meal_student', 'meal_public'

### ISSUE THREAD

**Issue by jayktee** [dcl-covid-19/mega-map-dev#3]
Deprecate meal_senior, meal_student, meal_public columns in favor of broader eligibility columns:

- instead of `meal_public`, use `public`
- instead of `meal_senior`, use `seniors`
- instead of `meal_student`, use `children`

We are also adding the following:

- homeless
- clients (e.g. serving registered clients only)
- uninsured
- residents (e.g. serving San Mateo residents only)

Also added these new columns to metadata.

**Comment by mfincker** [comment]
@jayktee - we are not using `meal_senior` anywhere.

The only place we use `meal_student` is to display it in the detailed view of a location if present.
<img width="497" alt="image" src="https://user-images.githubusercontent.com/7332285/83202080-d39e3480-a114-11ea-961c-bea898f7ea9e.png">
Should we remove the icon in the detailed view or keep the icon but display it when `children = 1` ?

Same question for `meal_public`?

Other eligibility types are not currently displayed. But now that we have more eligibility types, we need to revisit how to display it (filters vs. badges, inclusion vs. exclusion)

**Comment by jayktee** [comment]
Sounds good. 

- We should deprecate `meal_senior`, `meal_student` and `meal_public`. 
- Let's keep the icon and display it when `resource` = "meal" and `children` = 1.
- The eligibility is a bigger conversation that's related to our design questions around filters v tags v subcategories. Let's keep talking about this
