### ISSUE TITLE
Display the state of of fetchData in the result list

### ISSUE THREAD

**Issue by mfincker** [dcl-covid-19/mega-map-dev#30]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.
At the moment, we display "Loading ..." as long as markers == null. It would be great if instead we linked the message we display to the state of the fetchData request. We should display "Loading ..." wile waiting for a response, the results if we get them, or an error message if fetchData failed.

(b) What do we need to code next?
Probably create a fetchDataState and message variables in Results and pass them as props to resultsList.
Any new messages we display need to be translated - you can add them [here](https://docs.google.com/spreadsheets/d/17vQZZnKqq4IKXUDjHOsCCLYo0KTxUDsREE7b2Ev4Ang/edit#gid=0).

@llwu - I've tentatively assigned this to you since your previous PR touched upon this feature.

**Comment by llllvvuu** [comment]
Sounds good to me

**Comment by mfincker** [comment]
Reviewed and merged. Thanks @llwu !
