### ISSUE TITLE
Automate translation formatting

### ISSUE THREAD

**Issue by mfincker** [dcl-covid-19/mega-map-dev#33]
I currently manually export the translations from this [spreadsheet](https://docs.google.com/spreadsheets/d/17vQZZnKqq4IKXUDjHOsCCLYo0KTxUDsREE7b2Ev4Ang/edit#gid=0) and then use the `i18n-csv2json-cli` to turn them into `json` files.

But this cli  associates empty string to translation ids that don't have a translation. So I have to additionally remove these empty strings and reformat the `json` files to get valid i18n json files.

(a) Describe the feature
Would make our(my?^^) lives easier if we could write a script to automate the process, going from goggle spreadsheet to valid i18n files.

(b) How does it need to perform?
- can pull directly from the google spreadsheet (no need to export to csv first)
- creates valid translation files (no empty string for untranslated ids and json is properly formatted)
- run as a one line command (or even better but not necessray, can be integrated in the building workflow)

This could be a good issue for our data engineers if one of you is interested?  - @akatta13 , @16chuang , @jenren

**Comment by jenren** [comment]
Hey @mfincker! I'm not quite sure I understand -- could you describe again maybe what the ideal output is and what your current output is based on the current cli, with an example? I think that will help me get a better grasp on what needs to change.

**Comment by mfincker** [comment]
Hey @jenren , thanks for taking a look at this issue.

Here is an example of the current process. 

Imaging the translation spreadsheet contains these row:

Translation ID | en-US | fr-FR | es-ES
-- | -- | -- | -- | 
incomplete | incomplete |   | incomplete
complete | complete |  complet | complete

Firs,t I export the spreadsheet to a csv:
```
Translation ID,en-US,fr-FR,es-ES
incomplete,incomplete,,incomplete
complete,complete,complet,complete
```

Then I run  `i18n-csv2json-cli -f <this.csv> -t . -F`, which outputs one `json` file per langugage:
`en-US.i18n.json`
``` 
{
  "incomplete": "incomplete",
  "complete": "complete"
}
```
`es-ES?.i18n.json`
```
{
  "incomplete": "incomplete\r",
  "complete": "complete"
}
```
`fr-FR.i18n.json`
```
{
  "incomplete": "",
  "complete": "complet"
}
```

There are multiple issues with this output:

* the `json` files should simply be named `en.json`, `fr.json` and `es.json`
* the encoding for a new line character `\n` gets messed up and becomes `\r`
* the French `json` file should be:

```
{
  "complete": "complet"
}
```

Otherwise, the translation library considers that `""` is a valid translation and uses it in the website.

I have to manually correct all these mistakes in the `json` files but I think the correction should be scriptable. Let me know what you think! :)

**Comment by mfincker** [comment]
There is one more case to take into account, when the `json` is nested.

If the `en.json` is:
```
{
  "incomplete": "incomplete",
  "complete": "complete",
  "label": {
      "something": "translated"
  }
}
```

But `label.something` isn't translated in French, the module I use returns:
```
{
  "incomplete": "incomplete",
  "complete": "complete",
  "label": {
      "something": ""
  }
}
```

And I would want:
```
{
  "incomplete": "incomplete",
  "complete": "complete"
}
```

i.e. you need to remove empty strings and empty objects. Let me know if that makes sense.

**Comment by jayktee** [comment]
@akatta13 is this something you have time to look at? i can also provide more context on Slack.

**Comment by jayktee** [comment]
Completed with this script in [Data engineering repo](https://github.com/dcl-covid-19/mega-map/blob/master/modify_translations_CSV.Rmd)
