### ISSUE TITLE
4 Farmers Markets and 0 Safer Pickup Options for CalFresh/WIC retailers

### ISSUE THREAD

**Issue by charliehoffs** [dcl-covid-19/mega-map-dev#38]
**Describe the bug**
Currently we have 223 instances of "farmers_market" = 1 in the Google Sheets Mega Map Database but only 4 farmers markets show up when I toggle the "Farmer's Market" filter in the map. 

0 options show up when I check the "Safe-pick up options" filter on the map. That filter should pull from "curbside_pickup" = 1 or "delivery" = 1, which are populated in mega map dB. 

I believe this problem arose after we deployed the zipcode search bar.

**Comment by mfincker** [comment]
Fixed from the data side.
