### ISSUE TITLE
P-EBT Button

### ISSUE THREAD

**Issue by charliehoffs** [dcl-covid-19/mega-map-dev#39]
Please create a P-EBT button:

Description text: "Food benefits for kids who get free or reduced meals."
Button text: "Apply for P-EBT"
Link: https://ca.p-ebt.org/

Design for web (two options, button above or below "Welcome!"): https://www.canva.com/design/DAD93xHIk_A/B8LofryadGwBGR-dwxK19g/view?utm_content=DAD93xHIk_A&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

Design for mobile (two options):  https://www.canva.com/design/DAD-LRG_f6A/CN3Ck40evH30lwYeKVpLIg/view?utm_content=DAD-LRG_f6A&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by mfincker** [comment]
All ready to go.
![image](https://user-images.githubusercontent.com/7332285/83803289-4b6ee080-a67a-11ea-89a4-e57ebdf094cc.png)


Just waiting for the translations to deploy.

**Comment by behrman** [comment]
Nice work! Children in need will get food because of this button.

Let me suggest a small improvement. When the languages are Spanish and Chinese, have the link go to

https://ca.p-ebt.org/es
https://ca.p-ebt.org/zh

respectively, if possible.

**Comment by mfincker** [comment]
Done!
