### ISSUE TITLE
Add google analytics tracking

### ISSUE THREAD

**Issue by mfincker** [dcl-covid-19/mega-map-dev#4]
**Have an idea for an additional feature?**
(a) Describe the feature
Reuse NC code to enable google analytics.

(c) How will we code it?
Change gtag id and uncomment previous code chuncks.

**Comment by readingdancer** [comment]
FYI, we added the ability for these details to be stored in your own config file in this PR:

https://github.com/code-for-chapel-hill/NC-COVID-Support/pull/195
