### ISSUE TITLE
Style filter modal

### ISSUE THREAD

**Issue by mfincker** [dcl-covid-19/mega-map-dev#41]
Hi @topherauyeung ,

I've been working on refactoring the code to make adding / removing new categories easier. Part of this involved creating a new modal for filters (because some of the new categories we want to support will have lots of filters).

Right now it looks like that:
![image](https://user-images.githubusercontent.com/7332285/84415600-fb939a80-abe0-11ea-836a-3db4671f1451.png)

![image](https://user-images.githubusercontent.com/7332285/84415620-05b59900-abe1-11ea-93b9-4dfbdea39c91.png)

There are still a few bugs I'm working on but the main functionalities should be ready. Would you have some time to **improve the styling of the filter button** (both on large and small screens) because it is not very visible for the users at the moment.

**Any stylistic change is also welcome on the open modal.** :)

To give you an idea of a possible hierarchy in filters in the future categories, you can have a look at the filters in "free grocery" which has both nested and unested filters.

I've been working off the "filter-modal" branch. Please submit any PR to that branch (and hopefully I didn't forget to track a file this time ^^)

**Comment by jayktee** [comment]
@topherauyeung is this done? can i close?
