### ISSUE TITLE
Site languages

### ISSUE THREAD

**Issue by behrman** [dcl-covid-19/mega-map-dev#43]
I did a quick analysis of the languages other than English spoken at home in the Bay Area and California ([link](https://github.com/dcl-covid-19/mega-map/blob/master/eda/languages.md)). The data for California is for 42 languages.

The top 5 languages in decreasing order of the number of speakers is:

* Spanish
* Chinese
* Tagalog
* Vietnamese
* Korean

These are the top five for both for speakers of all English abilities and those who speak English less than "very well".

Malay does not appear separately in the 42 languages and is probably grouped with "Other languages of Asia", which ranks 17th.

If you want the site to have the languages that best match the population, I'd suggest replacing Malay with Korean.

**Comment by natastro** [comment]
Not sure if any translations are in questions but I'd be happy to help with any Spanish translation. Thank you!

**Comment by jayktee** [comment]
@natastro thanks so much for reaching out. Can i add you to our Slack workspace for better communication? Please email me at joyce.tagal (at) stanford.edu.

**Comment by stephencarico** [comment]
Note for future dev: a `ko.json` file does exist in the app with the option currently commented out in the `Header.vue` file. However, the bulk of this ticket will be to complete the `ko.json` file since it is only partially finished.
