### ISSUE TITLE
Bahasa Melayu hover and order

### ISSUE THREAD

**Issue by behrman** [dcl-covid-19/mega-map-dev#44]
I'm not an expert here, but open Googling, Bahasa Malayu appears to be Malay and not Burmese, which is the current hover text on the site.

Also, I'd suggest ordering the languages in the order of the number of speakers in the Bay Area. The top languages in order would be:

* Spanish
* Chinese
* Tagalog
* Vietnamese
* Korean

Malay doesn't appear separately in the statistics. I believe it is grouped in "Other languages of Asia", which is 23rd.

**Comment by llllvvuu** [comment]
This needs to be fixed in the translation spreadsheet first: It's broken in all languages:
```
src/locales/vi.json:    "ms": "Tiếng Myanma",
src/locales/ko.json:    "ms": "버마어",
src/locales/fr.json:    "ms": "birman",
src/locales/tl.json:    "ms": "Burmese",
src/locales/en.json:    "ms": "Burmese",
src/locales/ja.json:    "ms": "ビルマ語",
src/locales/ms.json:    "ms": "Burma",
src/locales/zh.json:    "ms": "缅甸语",
```

**Comment by jayktee** [comment]
Working on this.
