### ISSUE TITLE
Add new categories to drop down, list/map views

### ISSUE THREAD

**Issue by jayktee** [dcl-covid-19/mega-map-dev#49]
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.
Add 4 [new resource categories](https://docs.google.com/presentation/d/1DIOnJ-GNP71440-RzBeHBiU_qREeUmNh-Iwsslx5i5A/edit#slide=id.g87fd3ca162_0_2) to the dropdown menu (on the landing page) and ensure the list OR map-view for that resource has the right filters, badges and tooltip views. 

(b) What do we need to code next?

- Cash Assistance (resource = financial)
- Eviction resources (resource = legal_general_info; eviction = 1)
- Black owned restaurants (resource = bob)
- Domestic violence resources (resource = domviolence)

I've attached the Google slide that should explain all the above, but please reach out if any of this is unclear! In the Google slide, the variables in parentheses are the Carto variables that you should pull (e.g. med_urgent_care = 1). 

Suggest you start with one of the easier resources (cash assistance?) and we can review it before moving on to the next categories. 

DV resources will be complicated, suggest we set up a call to talk through this?

**Comment by charliehoffs** [comment]
(a) Describe the outcome needed/goal of the feature.
Election ballot drop-off locations for the 9 Bay Area counties

(b) What do we need to code next?
- Category: Ballot Drop-Off Locations (resource = ballot)
- Display Map
- List View:
> -Name
> -Address
>-Sort: Open today _(The List View "Sort" could be coded by all "Open 24 hours" sites and whenever "Open during business hours" is open?)_ > Distance

Badges
>-Outdoor
>-Indoor
>-Open 24 hours
>-Open today

Filters
>-Outdoor
>-Open 24 hours

-Tooltip view:
>-Name
>-Address
>-Hours
>-Weblink (scraped website link)
>-Notes: Drop off your election voting ballot at this location between October 5 and November 3! Thank you for doing your civic duty!
>-Last updated

**Comment by charliehoffs** [comment]
(a) Describe the outcome needed/goal of the feature.
School meal locations for Bay Area

(b) What do we need to code next?

Category: Free School Meals 
Display Map
List View:
>-Organization
>-Name
>-Address
>-url _(I know we've done phone number previously. I wonder if the link would be more helpful, but if this is big lift, it can totally wait)_
>-Sort: Open today > Serving all children > Distance

Badges
>- Open today
>- Child need be present
>- Must show ID
>- Serving all children
>- Only students enrolled in district

Filters
>- Open today
>- Child need be present
>- Must show ID
>- Serving all children

-Tooltip view:
>-Organization
>-Name
>-Address
>-url
>-Phone number
>-Hours
>-Weblink (scraped website link)
>-Notes
>-Last updated

**Comment by jayktee** [comment]
Completed with PR #49
