### ISSUE TITLE
Fix bug causing search block to appear in About Us and BLM statement

### ISSUE THREAD

**Issue by jayktee** [dcl-covid-19/mega-map-dev#57]
**Describe the bug**
The search block and BLM banner shows up in About Us and BLM statement pages. 

**To Reproduce**
1. Go to https://www.bayareacommunity.org/#/
2. Click on "About Us" or "Read our statement"
3. If you do a hard reset, the search block goes away.

**Expected behavior**
The About Us and BLM statement pages should not have the BLM banner or the search block

**Screenshots**
![image](https://user-images.githubusercontent.com/59407366/90457013-3d443400-e0af-11ea-9f99-64372328b69b.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
It's possible that the initialSearch parameter in App.js is responsible for this behavior. 
I also changed "needs" to "needs_name" to fix an error which may have caused this problem.
I did a [PR last week](https://github.com/dcl-covid-19/mega-map-dev/commit/090fdff04bd2215db19d65f9b35bee5636e20467) which may have broken things as well.

**Comment by topherauyeung** [comment]
Fixed!
