### ISSUE TITLE
Add "directions to here" on the expanded menu

### ISSUE THREAD

**Issue by jayktee** [dcl-covid-19/mega-map-dev#62]
**Have an idea for an additional feature?**
(a) Describe the feature
Adding "directions to here" on the expanded view for a location. "Directions to here" should sit at the very bottom of the business view card, and when clicked, should open marker at that location in Google Maps. See attached figma file (contact @jayktee for access).

https://www.figma.com/file/qPEgqcwOkKn2E6bQif4AKO/covid-website?node-id=263%3A139
![image](https://user-images.githubusercontent.com/59407366/93031724-f0864700-f5e1-11ea-956f-b39342c013d0.png)
![image](https://user-images.githubusercontent.com/59407366/93031730-fa0faf00-f5e1-11ea-9e4e-b93283f60674.png)

**Comment by chalkedgoose** [comment]
Hey @jayktee I'm interested in taking on the task is there anything I should note or is this good to go?

**Comment by jayktee** [comment]
hi @calba5141114 ! nice to meet you. nothing to note except that `staging` is main branch and all the deployment information should be on the Readme. Please slack me @joyce tagal on slack if you have any questions
