### ISSUE TITLE
Update website "About Us" to include unBox

### ISSUE THREAD

**Issue by charliehoffs** [dcl-covid-19/mega-map-dev#66]
Update the website interface's "About Us" to read as follows:

"We are a volunteer-driven, open-source project to help communities navigate the COVID crisis by providing information on public resources. We are a part of the organization [unBox](https://www.unboxproject.org/). This project began as a Bay Area school meals map, and now provides.... etc."

**Comment by yazminpa** [comment]
I think this issue can be closed now?

**Comment by charliehoffs** [comment]
Yes @yazminpa ! Good catch, thanks:)
