### ISSUE TITLE
Clicking on a site in sidebar takes me to a different location

### ISSUE THREAD

**Issue by jayktee** [dcl-covid-19/mega-map-dev#8]
**Describe the bug**
Clicking on sidebar entry for a site takes me to another site location and that site's sidebar entry.

**To Reproduce**

1. On desktop Chrome browser. Selected "SNAP/WIC Retailers" and "Friday". 
2. Zoomed into San Jose to see only the 3 locations there. 
![image](https://user-images.githubusercontent.com/59407366/81025952-65c05f00-8e2d-11ea-94c0-78667c816115.png)

3. Clicking on one of the sidebar entries, e.g. "Prime Time Nutrition 533", takes me to the sidebar entry for "Target 3265" in East Palo Alto
![image](https://user-images.githubusercontent.com/59407366/81025969-6d800380-8e2d-11ea-97ab-7661170ff17c.png).

4. The map also centres around Target 3265, I'm no longer in San Jose.

**Expected behavior**
I assumed clicking on the sidebar entry for Prime Time Nutrition (in the list) would take me to Prime Time Nutrition's entry.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 81.0.4044.129

**Comment by mfincker** [comment]
Good catch. This is the result of a partial implementation of sorting the list by distance from the center of the map. I have to think about how to fix that properly. For now, I am going to push a quick fix that will let you click on the list and get to the right location but the list and location will update when you move the map.

**Comment by readingdancer** [comment]
FYI, this was fixed in the NC COVID Support source with the PR: https://github.com/code-for-chapel-hill/NC-COVID-Support/pull/190

**Comment by mfincker** [comment]
Should not happen anymore since we are using the cartodb_id key column to map the maker with the selected list result.
